name: Build and Release YTMusicTweaked

on:
  workflow_dispatch:
    inputs: 
      decrypted_youtube_music_url:
        description: "The direct URL to the decrypted YouTube Music ipa (Upload a decrypted .ipa file to Dropbox and input its URL here.)"
        default: "https://www.dropbox.com/scl/fi/wpcg8dmuocntdwcst2wjw/com.google.ios.youtubemusic_7.26_und3fined.ipa?rlkey=qsa5jubw8mmwx9cr2oclglzt9&st=97dfirro&dl=1"
        required: true
        type: string    

      display_name:
        description: "App Name (Optional)"
        default: "YouTube Music"
        required: true
        type: string

      bundle_id:
        description: "BundleID (Optional)"
        default: "com.google.ios.youtubemusic"
        required: true
        type: string

  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build YTMusicUltimate
    runs-on: macos-15
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.7
        with:
          path: main
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make
              
      - name: Hide sensitive inputs
        uses: levibostian/action-hide-sensitive-inputs@v1

      - name: Cache Theos
        id: theos
        uses: actions/cache@v4.2.0
        env:
          cache-name: theos_cache_67db2ab
        with:
          path: theos/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}
      

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 

      - name: Setup Theos
        uses: actions/checkout@v4.1.7
        with:
          repository: theos/theos
          ref: 4bcc52914e0eeca719288522938185decaa8a1cb
          path: theos
          submodules: recursive
      
      - name: SDK Caching
        id: SDK
        uses: actions/cache@v4.2.0
        env:
          cache-name: iOS-16.4-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/arichornlover/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.4.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.1.7
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos
          
      - name: Install Azule
        run: |
          cd ${{ github.workspace }}/main
          git clone https://github.com/Al4ise/Azule 
          sudo ln -sf ~/Azule/azule /usr/local/bin/azule

      - name: Install cyan
        run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip


      - name: Prepare YouTube Music iPA
        id: prepare_youtube_music
        run: |
          wget "$YOUTUBE_MUSIC_URL" --no-verbose -O main/ytm.ipa

        env:
          YOUTUBE_MUSIC_URL: ${{ inputs.decrypted_youtube_music_url }}    


      - name: Build Tweak for Sideloading
        id: build_package
        run: |
          cd ${{ github.workspace }}/main
          make clean package SIDELOADING=1
        env:
          THEOS: ${{ github.workspace }}/theos


      - name: Inject tweak into provided IPA
        run: |
          git clone git://git.sv.gnu.org/coreutils
          cd ${{ github.workspace }}/main/packages
          tweakName=$(ls)
          cd ${{ github.workspace }}/main
          ./Azule/azule -i $PWD/ytm.ipa -o $PWD/packages/YTMusicUltimate.ipa -f $PWD/packages/$tweakName uwsf packages/$tweakName -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }} 




      - name: Remove the Watch folder
        run: |
          cd ${{ github.workspace }}/main/packages
          mv YTMusicUltimate.ipa YTMusicUltimate.zip
          unzip YTMusicUltimate.zip
          cd Payload/YoutubeMusic.app
          rm -rf Watch
          cd ../..
          zip -r YTMusicUltimate.ipa Payload
          rm -rf Payload    

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.5
        with:
          tag_name: YTMusicUltimate-v${{ github.run_number }}
          name: YTMusicUltimate-v${{ github.run_number }}
          files: main/packages/*.ipa
          draft: true
