name: Update Submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Git
        run: |
           git config --global user.email "actions@github.com"
           git config --global user.name "GitHub Actions"

      - name: Update YTMusicUltimateDX submodules
        run: |
          ref delete SponsorBlock-YouTubeMusicUpdate
          git submodule add https://github.com/Tori-Kinia/YouTubeMusicHeader.git Tweaks/YouTubeMusicHeader
          git submodule add https://github.com/Tori-Kinia/YTMABConfig.git Tweaks/YTMABConfig
          git submodule add https://github.com/Tori-Kinia/Return-YouTube-Dislikes.git Tweaks/Return-YouTube-Dislikes
          git submodule add https://github.com/Tori-Kinia/Return-YouTube-Music-Dislikes.git Tweaks/Return-YouTube-Music-Dislikes
          git submodule add https://github.com/kamtch/SponsorBlock-YouTubeMusicUpdate.git Tweaks/SponsorBlock-YouTubeMusic
          git add .
          git commit -m "Updated YTMusicUltimateDX submodules"
          git push origin
        continue-on-error: true

      - name: Check exit code
        run: |
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Submodule update failed with exit code $exit_code"
            exit 1
          fi
